linters-settings:
  container:
    exclude-rules:
      liveness-probe:
        - kind: DaemonSet
          name: csi-secrets-store
          container: csi-livenessprobe
        - kind: DaemonSet
          name: csi-secrets-store
          container: kube-rbac-proxy
        - kind: Deployment
          name: webhook
          container: kube-rbac-proxy
      readiness-probe:
        - kind: DaemonSet
          name: csi-secrets-store
          container: csi-livenessprobe
        - kind: DaemonSet
          name: csi-secrets-store
          container: kube-rbac-proxy
        - kind: Deployment
          name: webhook
          container: kube-rbac-proxy
        - kind: DaemonSet
          name: csi-secrets-store
          container: csi-node-driver-registrar
        - kind: DaemonSet
          name: csi-secrets-store
          container: secrets-store
  module:
    exclude-rules:
      license:
        directories:
          - images/csi-secrets-store-driver/secrets-store-csi-driver
          - images/vault-csi-provider/vault-csi-provider
