apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssi-controller
  namespace: d8-{{ $.Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "ssi-controller" )) | nindent 2 }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:secrets-store-integration:ssi-controller
  {{- include "helm_lib_module_labels" (list . (dict "app" "ssi-controller" )) | nindent 2 }}
rules:
- apiGroups:
  - deckhouse.io
  resources:
  - secretsstoreimports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - secretproviderclasses
  verbs:
  - get
  - create
  - update
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:secrets-store-integration:ssi-controller
  {{- include "helm_lib_module_labels" (list . (dict "app" "ssi-controller" )) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d8:secrets-store-integration:ssi-controller
subjects:
  - kind: ServiceAccount
    name: ssi-controller
    namespace: d8-{{ $.Chart.Name }}
