{{- define "vault_csi_provider_resources" }}
cpu: 10m
memory: 50Mi
{{- end }}

{{- $VAULT_CACERT_BYTES := "" }}
{{- if eq .Values.secretsStoreIntegration.connectionConfiguration "DiscoverLocalStronghold" }}
  {{ $VAULT_CACERT_BYTES = .Values.secretsStoreIntegration.internal.localStrongholdCaCert }}
{{- else if and .Values.secretsStoreIntegration.connection .Values.secretsStoreIntegration.connection.caCert }}
  {{- $VAULT_CACERT_BYTES = (.Values.secretsStoreIntegration.connection.caCert) }}
{{- end }}
{{- if (.Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vault-csi-provider
  namespace: d8-{{ $.Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "vault-csi-provider")) | nindent 2 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: vault-csi-provider
      minAllowed:
        {{- include "vault_csi_provider_resources" . | nindent 8 }}
      maxAllowed:
        cpu: 100m
        memory: 200Mi
  targetRef:
    apiVersion: "apps/v1"
    kind: DaemonSet
    name: vault-csi-provider
  updatePolicy:
    updateMode: "Initial"
{{- end }}
{{- if or (.Values.global.discovery.apiVersions | has "deckhouse.io/v1alpha1/SecurityPolicyException") (.Capabilities.APIVersions.Has "deckhouse.io/v1alpha1/SecurityPolicyException") }}
---
apiVersion: deckhouse.io/v1alpha1
kind: SecurityPolicyException
metadata:
  name: vault-csi-provider
  namespace: d8-{{ $.Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "vault-csi-provider")) | nindent 2 }}
spec:
  securityContext:
    readOnlyRootFilesystem:
      allowedValue: true
      metadata:
        description: |
          Ensures the container's root filesystem is mounted read-only.
    allowPrivilegeEscalation:
      allowedValue: false
      metadata:
        description: |
          Vault CSI provider does not require privilege escalation.
    seccompProfile:
      allowedValues:
        - RuntimeDefault
      metadata:
        description: |
          Uses the default seccomp profile from the container runtime for system call filtering.
    runAsNonRoot:
      allowedValue: false
      metadata:
        description: |
          Vault CSI provider runs as root to access the provider socket.
    privileged:
      allowedValue: false
      metadata:
        description: |
          Vault CSI provider does not require privileged mode.
    capabilities:
      allowedValues:
        drop:
          - ALL
      metadata:
        description: |
          Drops all Linux capabilities to minimize the attack surface.
    runAsUser:
      allowedValues:
      - 0
      metadata:
        description: |
          Runs as root (0) to access the provider socket directory.
  volumes:
    types:
      allowedValues:
      - hostPath
      metadata:
        description: |
          Vault CSI provider requires hostPath volume to expose its gRPC socket.
    hostPath:
      allowedValues:
        - path: "/var/run/secrets-store-csi-providers"
          metadata:
            description: |
              Required for exposing the Vault CSI provider gRPC socket to the CSI driver.
{{- end }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vault-csi-provider
  namespace: d8-{{ $.Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "vault-csi-provider")) | nindent 2 }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-csi-provider
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-csi-provider
        security.deckhouse.io/security-policy-exception: vault-csi-provider
    spec:
      serviceAccountName: vault-csi-provider
      automountServiceAccountToken: true
      {{- include "ssi.imagePullSecrets" . | nindent 6 }}
      {{- include "helm_lib_tolerations" (tuple . "any-node") | nindent 6 }}
      {{- include "helm_lib_priority_class" (tuple . "cluster-medium") | nindent 6 }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_root" . | nindent 6 }}
      containers:
        - name: vault-csi-provider
          image: {{ include "helm_lib_module_image" (list . "vaultCsiProvider") }}
          imagePullPolicy: IfNotPresent
          {{- include "module_container_security_context_readonly_fs_flexible" (dict "uid" 0) | nindent 10 }}
          env:
          {{- if $VAULT_CACERT_BYTES }}
          - name: VAULT_CACERT_BYTES
            value: |
              {{- $VAULT_CACERT_BYTES | nindent 14 }}
          {{- end }}
          args:
            {{- if eq .Values.secretsStoreIntegration.connectionConfiguration "Manual" }}
            - -vault-addr={{ .Values.secretsStoreIntegration.connection.url }}
            {{- else }}
            - -vault-addr=https://stronghold.d8-stronghold.svc:8300
            {{- end }}
            {{- if and (.Values.secretsStoreIntegration.connection) (hasKey .Values.secretsStoreIntegration.connection "authPath") (ne .Values.secretsStoreIntegration.connection.authPath "") }}
            - -vault-mount={{ .Values.secretsStoreIntegration.connection.authPath }}
            {{- else }}
            - -vault-mount=kubernetes_local
            {{- end }}
            {{- if and (.Values.secretsStoreIntegration.connection) (hasKey .Values.secretsStoreIntegration.connection "namespace") (ne .Values.secretsStoreIntegration.connection.namespace "") }}
            - -vault-namespace={{ .Values.secretsStoreIntegration.connection.namespace }}
            {{- end }}
            - -endpoint=/provider/vault.sock
            - -debug=false
          resources:
            requests:
              {{- include "helm_lib_module_ephemeral_storage_only_logs" . | nindent 14 }}
            {{- if not (.Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
              {{- include "vault_csi_provider_resources" . | nindent 14 }}
            {{- end }}
          volumeMounts:
            - name: providervol
              mountPath: "/provider"
          livenessProbe:
            httpGet:
              path: "/health/ready"
              port: 8080
              scheme: "HTTP"
            failureThreshold: 2
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: "/health/ready"
              port: 8080
              scheme: "HTTP"
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
      volumes:
        - name: providervol
          hostPath:
            path: "/var/run/secrets-store-csi-providers"
