---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: d8-{{ $.Chart.Name }}-mutating-webhook-configuration
  {{- include "helm_lib_module_labels" (list . (dict "app" "vault-secrets-webhook")) | nindent 2 }}
webhooks:
- name: pods.vault-secrets-webhook.admission.deckhouse.io
  admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      namespace: d8-{{ $.Chart.Name }}
      name: vault-secrets-webhook
      path: /pods
    caBundle: {{ .Values.secretsStoreIntegration.internal.webhookCert.ca | b64enc | quote }}
  rules:
  - operations:
    - CREATE
    apiGroups:
    - "*"
    apiVersions:
    - "*"
    resources:
    - pods
  failurePolicy: Fail
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
    - key: heritage
      operator: NotIn
      values:
        - deckhouse
  objectSelector:
    matchExpressions:
    - key: stronghold.deckhouse.io/mutate
      operator: NotIn
      values:
      - skip
  sideEffects: NoneOnDryRun
  timeoutSeconds: 3
