---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vault-secrets-webhook
  namespace: d8-{{ $.Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "vault-secrets-webhook")) | nindent 2 }}
spec:
  minAvailable: {{ include "helm_lib_is_ha_to_value" (list . 1 0) }}
  selector:
    matchLabels:
      app: vault-secrets-webhook
