apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets-webhook
  namespace: {{ include "ssi.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "vault-secrets-webhook" )) | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-secrets-webhook-cluster-role
  {{- include "helm_lib_module_labels" (list . (dict "app" "vault-secrets-webhook" )) | nindent 2 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-secrets-webhook-cluster-role-binding
  {{- include "helm_lib_module_labels" (list . (dict "app" "vault-secrets-webhook" )) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-secrets-webhook-cluster-role
subjects:
  - kind: ServiceAccount
    name: vault-secrets-webhook
    namespace: {{ include "ssi.namespace" . }}
