apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets-webhook
  namespace: d8-{{ $.Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "vault-secrets-webhook" )) | nindent 2 }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:secrets-store-integration:vault-secrets-webhook
  {{- include "helm_lib_module_labels" (list . (dict "app" "vault-secrets-webhook" )) | nindent 2 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:secrets-store-integration:vault-secrets-webhook
  {{- include "helm_lib_module_labels" (list . (dict "app" "vault-secrets-webhook" )) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d8:secrets-store-integration:vault-secrets-webhook
subjects:
  - kind: ServiceAccount
    name: vault-secrets-webhook
    namespace: d8-{{ $.Chart.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:secrets-store-integration:vault-secrets-webhook:rbac-proxy
  {{- include "helm_lib_module_labels" (list . (dict "app" "vault-secrets-webhook")) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d8:rbac-proxy
subjects:
- kind: ServiceAccount
  name: vault-secrets-webhook
  namespace: d8-{{ $.Chart.Name }}
