---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: vault-secrets-webhook-tls
  namespace: {{ include "ssi.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "vault-secrets-webhook")) | nindent 2 }}
data:
  ca.crt: {{ .Values.secretsStoreIntegration.internal.webhookCert.ca | b64enc }}
  tls.crt: {{ .Values.secretsStoreIntegration.internal.webhookCert.crt | b64enc }}
  tls.key: {{ .Values.secretsStoreIntegration.internal.webhookCert.key | b64enc }}
