---
apiVersion: v1
kind: Service
metadata:
  name: vault-secrets-webhook
  namespace: {{ include "ssi.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "vault-secrets-webhook")) | nindent 2 }}
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: 8443
  selector:
    app: vault-secrets-webhook
