---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretsstoreimports.deckhouse.io
  labels:
    heritage: deckhouse
    module: secrets-store-integration
spec:
  group: deckhouse.io
  names:
    kind: SecretsStoreImport
    listKind: SecretsStoreImportList
    plural: secretsstoreimports
    singular: secretsstoreimport
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: |
           Namespaced Kubernetes Custom resource for mapping between Vault-compatible storage and filename in container
        required:
          - spec
        properties:
          spec:
            type: object
            required:
              - type
              - role
              - files
            properties:
              type:
                type: string
                enum: ["CSI"]
                description: Only mode CSI supported
              role:
                type: string
                pattern: ^[-_\.a-zA-Z0-9]+$
                description: Role in vault-compatible storage
              authPath:
                type: string
                pattern: ^[-_.a-zA-Z0-9]+$
                description: Auth path in vault-compatible storage
              namespace:
                type: string
                pattern: ^[-_./a-zA-Z0-9]+$
                description: Namespace where secret is stored
              address:
                type: string
                pattern: ^https?://[.:0-9a-zA-Z-]+$
                description: Address of vault-compatible storage
              caCert:
                type: string
                pattern: "^-----BEGIN CERTIFICATE-----\n(.+\n){5}"
                description: |
                  Stronghold or vault CA in PEM format
              audience:
                type: string
                description: JWT audience
              skipTLSVerify:
                type: boolean
                description: Skip TLS verification
              files:
                type: array
                items:
                  type: object
                  required:
                    - source
                    - name
                  properties:
                    name:
                      type: string
                      pattern: ^[-_a-zA-Z0-9.]+$
                      description: Filename to create
                    source:
                      type: object
                      required:
                      - path
                      - key
                      properties:
                        path:
                          type: string
                          pattern: ^[-a-zA-Z0-9_.\/]+$
                          description: Vault secretPath
                        key:
                          type: string
                          pattern: ^[-a-zA-Z0-9_.]+$
                          description: Vault secretKey
