---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretsstoreimports.deckhouse.io
  labels:
    heritage: deckhouse
    module: secrets-store-integration
spec:
  group: deckhouse.io
  names:
    kind: SecretsStoreImport
    listKind: SecretsStoreImportList
    plural: secretsstoreimports
    singular: secretsstoreimport
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: |
           Namespaced resource to define mapping between Vault-compatible storage and files in containers.
        required:
          - spec
        properties:
          spec:
            type: object
            required:
              - type
              - role
              - files
            properties:
              type:
                type: string
                enum: ["CSI"]
                description: |
                  Type of a mechanism for delivering secrets into the cluster.
                  
                  Only the CSI type is supported at the moment.
              role:
                type: string
                pattern: ^[-_\.a-zA-Z0-9]+$
                description: Role in a Vault-compatible storage.
              authPath:
                type: string
                pattern: ^[-_.a-zA-Z0-9]+$
                description: |
                  Authentication mount path in a Vault-compatible storage.
                  
                  If the parameter is not specified, the value from ModuleConfig is used.
              namespace:
                type: string
                pattern: ^[-_./a-zA-Z0-9]+$
                description: |
                  Namespace where the imported secret is created.
                  
                  If the parameter is not specified, the value from ModuleConfig is used.
              address:
                type: string
                pattern: ^https?://[.:0-9a-zA-Z-]+$
                description: |
                  Address of a Vault-compatible storage.
                  
                  If the parameter is not specified, the value from ModuleConfig is used.
              caCert:
                type: string
                pattern: "^-----BEGIN CERTIFICATE-----\n(.+\n){5}"
                description: |
                  CA certificate in PEM format for connecting to Stronghold or Vault. 
                  
                  If the parameter is not specified, the value from ModuleConfig is used.
              audience:
                type: string
                description: JWT token recipient audience (`aud` claim in a token).
              skipTLSVerify:
                type: boolean
                description: Skips verification of TLS certificates.
              files:
                type: array
                items:
                  type: object
                  required:
                    - source
                    - name
                  properties:
                    name:
                      type: string
                      pattern: ^[-_a-zA-Z0-9.]+$
                      description: Filename where the secret is written.
                    decodeBase64:
                      type: boolean
                      default: false
                      description: Enables decoding of a Base64-encoded secret value before saving it to a file.
                    source:
                      type: object
                      required:
                      - path
                      - key
                      properties:
                        path:
                          type: string
                          pattern: ^[-a-zA-Z0-9_.\/]+$
                          description: Path to the secret in a Vault-compatible KV store.
                        key:
                          type: string
                          pattern: ^[-a-zA-Z0-9_.]+$
                          description: Secret key name in a Vault-compatible KV store.
