---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "ssi.namespace" . }}
  {{- include "helm_lib_module_labels" (list $ (dict "app" (include "ssi.name" $ ) "prometheus.deckhouse.io/rules-watcher-enabled" "true" )) | nindent 2 }}
---
{{- include "helm_lib_kube_rbac_proxy_ca_certificate" (list . (printf "d8-%s" .Chart.Name)) }}
