{{- if .Values.secretsStoreIntegration.registry }}
{{- with .Values.secretsStoreIntegration.registry.dockercfg }}
---
apiVersion: v1
kind: Secret
metadata:
  name: module-registry
  namespace: {{ include "ssi.namespace" . }}
  {{- include "helm_lib_module_labels" (list $ (dict "app" (include "ssi.name" $ ) )) | nindent 2 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ . }}
{{- end }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: deckhouse-registry
  namespace: {{ include "ssi.namespace" . }}
  {{- include "helm_lib_module_labels" (list $ (dict "app" $.Chart.Name )) | nindent 2 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.registry.dockercfg }}
{{- end }}
