{{- if .Values.secretsStoreIntegration.registry }}
{{- with .Values.secretsStoreIntegration.registry.dockercfg }}
---
apiVersion: v1
kind: Secret
metadata:
  name: module-registry
  namespace: d8-{{ $.Chart.Name }}
  {{- include "helm_lib_module_labels" (list $ (dict "app" $.Chart.Name )) | nindent 2 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ . }}
{{- end }}
{{- else }}
{{- if .Values.global.registry }}
{{- with .Values.global.registry.dockercfg }}
---
apiVersion: v1
kind: Secret
metadata:
  name: deckhouse-registry
  namespace: d8-{{ $.Chart.Name }}
  {{- include "helm_lib_module_labels" (list $ (dict "app" $.Chart.Name )) | nindent 2 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ . }}
{{- end }}
{{- end }}
{{- end }}
