name: Build and push for dev

env:
  CI_COMMIT_REF_NAME: ${{ github.ref_name }}

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  dev_setup_build:
    runs-on: ubuntu-latest
    name: Build and Push images
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.DEV_REGISTRY }}
          registry_login: ${{ vars.DEV_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.DEV_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/build@v2
        with:
          module_source: ${{ vars.DEV_MODULE_SOURCE }}
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: $(echo pr${{ github.ref_name }} | sed 's/\/.*//g')
