name: Build and push for dev

env:
  CI_COMMIT_REF_NAME: ${{ github.ref_name }}
  WERF_FINAL_IMAGES_ONLY: "true"

on:
  pull_request:
  # call from trivy_image_check.yaml, which in turn call from pull_request
  push:
    branches:
      - main
  workflow_call:

jobs:
  dev_setup_build:
    runs-on: ubuntu-latest
    name: Build and Push images
    steps:
      - name: Set vars for PR
        if: ${{ github.ref_name != 'main' }}
        run: |
          MODULES_MODULE_TAG="$(echo pr${{ github.ref_name }} | sed 's/\/.*//g')"
          echo "MODULES_MODULE_TAG=$MODULES_MODULE_TAG" >> "$GITHUB_ENV"
      - name: Set vars for main
        if: ${{ github.ref_name == 'main' }}
        run: |
          echo "MODULES_MODULE_TAG=${{ github.ref_name }}" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: deckhouse/modules-actions/setup@v4
        with:
          registry: ${{ vars.DEV_REGISTRY }}
          registry_login: ${{ vars.DEV_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.DEV_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/build@v4
        with:
          module_source: ${{ vars.DEV_MODULE_SOURCE }}
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: ${{ env.MODULES_MODULE_TAG }}
