name: PR Checks
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Lint
    steps:
      - uses: actions/checkout@v5
      - uses: deckhouse/modules-actions/lint@v5
