name: PR Checks

env:
  DMT_VERSION: ${{ vars.DMT_VERSION }}
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  release-label:
    name: Release note label
    runs-on: ubuntu-latest

    steps:
      - name: Check minimum labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "release-note/dependencies, dependencies, release-note/deprecation, release-note/breaking-change, release-note/bug, bug, release-note/enhancement, enhancement, release-note/documentation, documentation, release-note/new-feature, release-note/ignore"

  linter:
    name: DMT linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get DMT
        run: |
          wget -qO- https://github.com/deckhouse/dmt/releases/download/v${DMT_VERSION}/dmt-${DMT_VERSION}-linux-amd64.tar.gz | gunzip | tar xvf - -C /tmp
        shell: bash
      - name: Lint with DMT
        run: |
          /tmp/dmt-${DMT_VERSION}-linux-amd64/dmt lint
        shell: bash

