on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'release branch name, example: release-1.68'
        required: false

jobs:
  cve_scan:
    runs-on: ubuntu-latest
    name: Trivy CVE Scan
    steps:
      - uses: actions/checkout@v4
      - name: Sets env vars for PR
        run: |
          echo "MODULE_IMAGE_TAG=pr${{ github.event.number }}" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'
      - name: Sets env vars for manual run
        run: |
          echo "MODULE_IMAGE_TAG=${{ github.event.inputs.release_branch || 'main' }}" >> $GITHUB_ENV
        if: github.event_name == 'workflow_dispatch'
      - uses: deckhouse/modules-actions/cve_scan@v2
        with:
          image: ${{vars.DEV_MODULE_SOURCE}}/${{vars.MODULE_NAME}}
          tag: ${{ env.MODULE_IMAGE_TAG || 'main' }}
          module_name: ${{ vars.MODULE_NAME }}
          dd_url: ${{vars.DEFECTDOJO_HOST}}
          dd_token: ${{secrets.DEFECTDOJO_API_TOKEN}}
          trivy_registry: ${{vars.TRIVY_REGISTRY}}
          trivy_registry_user: ${{ vars.TRIVY_REGISTRY_USER }}
          trivy_registry_password: ${{ secrets.TRIVY_REGISTRY_PASSWORD }}
          deckhouse_private_repo: ${{vars.DECKHOUSE_PRIVATE_REPO}}
