name: Deploy Dev

env:
  CI_COMMIT_REF_NAME: ${{ github.event.inputs.tag }}
  WERF_FINAL_IMAGES_ONLY: "true"

on:
  workflow_dispatch:
    inputs:
      channel:
        description: "Select release channel"
        type: choice
        default: alpha
        options:
          - "alpha"
          - "beta"
          - "early-access"
          - "stable"
          - "rock-solid"

      tag:
        description: "The module's tag, which must include the -dev1 postfix. For example: v1.21.1-dev1"
        type: string
        required: true

      enableBuild:
        type: boolean
        default: true
        description: 'Set to true if build is required'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy dev
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/setup@v4
        with:
          registry: ${{ vars.DEV_REGISTRY }}
          registry_login: ${{ vars.DEV_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.DEV_MODULES_REGISTRY_PASSWORD }}
      - if: ${{ github.event.inputs.enableBuild == 'true' }}
        uses: deckhouse/modules-actions/build@v4
        with:
          module_source: "${{ vars.DEV_MODULE_SOURCE }}"
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: $(echo pr${{ github.ref_name }} | sed 's/\/.*//g')
      - uses: deckhouse/modules-actions/deploy@v4
        with:
          module_source: ${{ vars.DEV_MODULE_SOURCE }}
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: ${{ github.event.inputs.tag }}
          release_channel: ${{ github.event.inputs.channel }}
