name: Deploy Prod

env:
  CI_COMMIT_REF_NAME: ${{ github.ref_name }}

on:
  workflow_dispatch:
   inputs:
      version:
        description: "Select version"
        type: choice
        default: alpha
        options:
          - "alpha"
          - "beta"
          - "early-access"
          - "stable"
          - "rock-solid"

      ce:
        type: boolean
        description: CE
      be:
        type: boolean
        description: BE
      se:
        type: boolean
        description: SE
      se-plus:
        type: boolean
        description: SE+
      ee:
        type: boolean
        description: EE
      fe:
        type: boolean
        description: FE

      tag:
        description: "Tag of the module, example v1.21.1"
        type: string
        required: true

jobs:
  job-CE:
    name: Edition CE
    runs-on: ubuntu-latest
    if: github.event.inputs.ce == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.PROD_REGISTRY }}
          registry_login: ${{ vars.PROD_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/deploy@v2
        with:
          module_source: "${{ vars.PROD_REGISTRY }}/${{ vars.PROD_MODULE_SOURCE_NAME }}/ce/modules"
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: ${{ github.event.inputs.tag }}
          release_channel: ${{ github.event.inputs.channel }}

  job-EE:
    name: Edition EE
    runs-on: ubuntu-latest
    if: github.event.inputs.ee == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.PROD_REGISTRY }}
          registry_login: ${{ vars.PROD_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/deploy@v2
        with:
          module_source: "${{ vars.PROD_REGISTRY }}/${{ vars.PROD_MODULE_SOURCE_NAME }}/ee/modules"
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: ${{ github.event.inputs.tag }}
          release_channel: ${{ github.event.inputs.channel }}

  job-FE:
    name: Edition FE
    runs-on: ubuntu-latest
    if: github.event.inputs.fe == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.PROD_REGISTRY }}
          registry_login: ${{ vars.PROD_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/deploy@v2
        with:
          module_source: "${{ vars.PROD_REGISTRY }}/${{ vars.PROD_MODULE_SOURCE_NAME }}/fe/modules"
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: ${{ github.event.inputs.tag }}
          release_channel: ${{ github.event.inputs.channel }}

  job-BE:
    name: Edition BE
    runs-on: ubuntu-latest
    if: github.event.inputs.be == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.PROD_REGISTRY }}
          registry_login: ${{ vars.PROD_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/deploy@v2
        with:
          module_source: "${{ vars.PROD_REGISTRY }}/${{ vars.PROD_MODULE_SOURCE_NAME }}/be/modules"
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: ${{ github.event.inputs.tag }}
          release_channel: ${{ github.event.inputs.channel }}

  job-SE:
    name: Edition SE
    runs-on: ubuntu-latest
    if: github.event.inputs.se == 'true'
    steps:
      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.PROD_REGISTRY }}
          registry_login: ${{ vars.PROD_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/deploy@v2
        with:
          module_source: "${{ vars.PROD_REGISTRY }}/${{ vars.PROD_MODULE_SOURCE_NAME }}/se/modules"
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: ${{ github.event.inputs.tag }}
          release_channel: ${{ github.event.inputs.channel }}

  job-SE-plus:
    name: Edition SE+
    runs-on: ubuntu-latest
    if: github.event.inputs.se-plus == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ vars.PROD_REGISTRY }}
          registry_login: ${{ vars.PROD_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/deploy@v2
        with:
          module_source: "${{ vars.PROD_REGISTRY }}/${{ vars.PROD_MODULE_SOURCE_NAME }}/se-plus/modules"
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: ${{ github.event.inputs.tag }}
          release_channel: ${{ github.event.inputs.channel }}
