name: Cleanup dev registry

on:
  workflow_dispatch:
  schedule:
    - cron: "12 0 * * 6"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Cleanup images
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/setup@v4
        with:
          registry: ${{ vars.DEV_REGISTRY }}
          registry_login: ${{ vars.DEV_MODULES_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.DEV_MODULES_REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/cleanup@v1
        with:
          module_source: ${{ vars.DEV_MODULE_SOURCE }}
          module_name: ${{ vars.MODULE_NAME }}
          module_tag: ${{ github.ref_name }}
